kind: pipeline
type: exec
name: build-and-deploy-test

steps:
  - name: update-code
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
    commands:
      - echo $GITHUB_TOKEN
      - echo $GITHUB_USERNAME
      - cd /home/kodanim/test || exit 1
      - git config --global --add safe.directory /home/kodanim/test
      - git remote set-url origin https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/Kodanim/test.git
      - git pull

  - name: install-deps
    commands:
      - cd /home/kodanim/test || exit 1
      - npm install

  - name: build
    commands:
      - cd /home/kodanim/test || exit 1
      - npm run build

  - name: deploy
    commands:
      - rsync -av /home/kodanim/test/dist/ /srv/web/test

