kind: pipeline
type: exec
name: build-and-deploy-test

steps:
  - name: install-deps
    commands:
      - npm install  # inutile de faire 'cd', Drone commence déjà dans DRONE_WORKSPACE

  - name: build
    commands:
      - npm run build

  - name: deploy
    commands:
      - rsync -av ${DRONE_WORKSPACE}/dist/ /srv/web/test
