kind: pipeline
type: exec
name: build-and-deploy-test

steps:
  - name: install-deps
    commands:
      - cd /home/kodanim/test || exit 1
      - npm install

  - name: build
    commands:
      - cd /home/kodanim/test || exit 1
      - npm run build

  - name: deploy
    commands:
      - rsync -av /home/kodanim/test/dist/ /srv/web/test

